description: "sensu-redis-simple-test"
builds:
- platform: "linux"
  arch: "amd64"
  annotations:
    io.sensu.bonsai.tags: check, redis
  asset_filename: "sensu-redis-simple-test-0.0.4.tar.gz"
  sha_filename: "sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
