description: "sensu-redis-simple-test"
builds:
- platform: "linux"
  arch: "amd64"
  asset_filename: "sensu-redis-simple-test-0.0.3.tar.gz"
  sha_filename: "sensu-redis-simple-test-0.0.3-sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
